config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'pages/about', to: 'pages#about'
  
  resources :articles do
    resources :comments
  end
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :comments, dependent: :destroy

    validates :user_id, presence: true
    validates :title, presence: true, length: { minimum: 2, maximum: 50 }
    validates :author, presence: true
    validates :publisher, presence: true
    validates :book_page, presence: true
    validates :line, presence: true, length: { minimum: 3, maximum: 300 }
    validates :description, presence: true, length: { minimum: 10, maximum: 1000 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 1000 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  has_many :comments
  before_save { self.email = email.downcase }
  
  validates :username, presence: true, uniqueness: { case_sensitive: false }, 
  length: { minimum: 3, maximum: 25 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false}, 
  length: { maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user  # current_user를 갖고 있으면 true를 return함
  end
  
  def require_user  # 로그인되어 있지 않을 때의 제한사항
    if !logged_in?
      flash[:danger] = "로그인이 필요합니다"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   before_action :set_article, only: [:show, :edit, :update, :destroy]
   before_action :require_user, except: [:index, :show]
   before_action :require_same_user, only: [:edit, :update, :destroy]

   def index
      @articles = Article.paginate(page: params[:page], per_page: 10).order("created_at DESC") # 내림차순으로 정렬
   end
   
   def new
       @article = Article.new
   end
   
   def create
       @article = Article.new(article_params)
       @article.user = current_user
       if @article.save
           flash[:success] = "당신의 울림이 게시되었습니다!"
           redirect_to article_path(@article)
       else
           render 'new'
       end
   end
   
   def show
      @comments = Comment.where(article_id: @article)
   end
   
   def edit
   end
   
   def update
       if @article.update(article_params)
           flash[:success] = "글이 성공적으로 수정되었습니다"
           redirect_to article_path(@article)
       else
           render 'edit'
       end
   end
   
   def destroy
      @article.destroy
      flash[:success] = "글이 성공적으로 삭제되었습니다"
      redirect_to articles_path
   end
   
   private
   def set_article
      @article = Article.find(params[:id])
   end
   
   def article_params
      params.require(:article).permit(:title, :author, :publisher, :book_page, :line, :description) 
   end
   
   def require_same_user
      if current_user != @article.user and !current_user.admin?
         flash[:danger] = "자신이 쓴 글만 수정/삭제할 수 있습니다"
         redirect_to root_path
      end
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_article
  before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
  before_action :comment_owner, only: [:destroy, :edit, :update]
  def create
    if session[:user_id] != nil
      @comment = @article.comments.create(params[:comment].permit(:content))
      @comment.user_id = current_user.id
      @comment.save
      redirect_to article_path(@article)
    else
      flash[:danger] = "로그인 후 이용해 주세요!"
      redirect_to article_path(@article)
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to article_path(@article)
  end
  
  def edit
    
  end
  
  def update
    if @comment.update(params[:comment].permit(:content))
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  private
  def find_article
    @article = Article.find(params[:article_id])
  end
  
  def find_comment
    @comment = @article.comments.find(params[:id])
  end
  
  def comment_owner
    unless current_user.id == @comment.user_id
      flash[:notice] = "허용되지 않는 접근 방식입니다!"
      redirect_to @article
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def home
      redirect_to articles_path if logged_in?
   end
   
   def about
       
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "로그인 되었습니다!"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "로그인 정보를 확인해 주세요"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:success] = "로그아웃 되었습니다!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "울림: 회원가입이 완료되었습니다!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:success] = "계정이 성공적으로 수정되었습니다!"
      redirect_to articles_path
    else
      render 'edit'
    end
  end
  
  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 10)
  end
  
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "사용자의 모든 게시글과 사용자가 삭제되었습니다"
    redirect_to users_path
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "자신이 쓴 글만 수정할 수 있습니다"
      redirect_to root_path
    end
  end
  
  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "admin만 가능합니다!"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
            <%= truncate(article.line, length: 220) %>
        </div>
        <div class="article-meta-details">
            Created by <i><%= article.user.username if article.user %></i>, <%= time_ago_in_words(article.created_at) %> ago&nbsp;&nbsp;&nbsp;&nbsp;&#124;&nbsp;&nbsp;&nbsp;&nbsp;last updated: <%= time_ago_in_words(article.updated_at) %> ago
        </div>
        <% if logged_in? && (current_user == article.user || current_user.admin?) %>
          <div class="article-actions">
              <%= link_to "수정", edit_article_path(article), class: "btn btn-xs btn-primary" %>
              <%= link_to "삭제", article_path(article), method: :delete,
              data: { confirm: "정말 삭제하시겠습니까?"},
              class: "btn btn-xs btn-danger" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
    <div class="col-xs-12">
      <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
         <div class="form-group"> <!--책제목을 입력 받음-->
             <div class="control-label col-sm-2">
                 <%= f.label :title %>
             </div>
             <div class="col-sm-8">
                 <%= f.text_field :title, class: "form-control", placeholder: "책 제목을 입력하세요", autofocus: true %>
             </div>
         </div>
         <div class="form-group"> <!--저자를 입력 받음-->
             <div class="control-label col-sm-2">
                 <%= f.label :author %>
             </div>
             <div class="col-sm-8">
                 <%= f.text_field :author, class: "form-control", placeholder: "저자를 입력하세요" %>
             </div>
         </div>
         <div class="form-group"> <!--출판사를 입력 받음-->
             <div class="control-label col-sm-2">
                 <%= f.label :publisher %>
             </div>
             <div class="col-sm-8">
                 <%= f.text_field :publisher, class: "form-control", placeholder: "출판사를 입력하세요" %>
             </div>
         </div>
         <div class="form-group"> <!--페이지를 입력 받음-->
             <div class="control-label col-sm-2">
                 <%= f.label :book_page %>
             </div>
             <div class="col-sm-8">
                 <%= f.number_field :book_page, class: "form-control", placeholder: "몇 페이지에 있는 문장인가요?" %>
             </div>
         </div>
         <div class="form-group"> <!--문장을 입력 받음-->
             <div class="control-label col-sm-2">
                 <%= f.label :line %>
             </div>
             <div class="col-sm-8">
                 <%= f.text_area :line, rows: 5, class: "form-control", placeholder: "당신에게 울림을 전달한, 그 문장을 적어주세요" %>
             </div>
         </div>
         <div class="form-group"> <!--user의 comment를 입력 받음-->
             <div class="control-label col-sm-2">
                 <%= f.label :description %>
             </div>
             <div class="col-sm-8">
                 <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "이 문장을 고른 이유, 느낀점 등을 자유롭게 써주세요" %>
             </div>
         </div>
         <div class="form-group">
             <div class="col-sm-offset-2 col-sm-10">
                 <%= f.submit class: 'btn btn-primary btn-lg' %>
             </div>
         </div>
     <% end %>
     <div class="col-xs-4 col-xs-offset-4">
         [ <%= link_to "목록으로 돌아가기", articles_path %> ]
     </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">수정하기</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">모든 글 보기</h1>

<div align="center">
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center">새 글 쓰기</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">도서명:&nbsp;&nbsp;&nbsp;&nbsp;<strong><%= @article.title %></strong></h2>
<div class="well col-xs-8 col-xs-offset-2">
	<h6><%= @article.author %>&nbsp;(지은이)&nbsp;&nbsp;&#124;&nbsp;&nbsp;<%= @article.publisher %>&nbsp;(출판사)</h6><hr>
	<h4 class="description"><b><%= @article.user.username %>'s PICK!</b></h4>
	<p class="show-line"><i><%= @article.line %></i></p>
	<p class="page">&nbsp;&mdash;&nbsp;<%= @article.book_page %>쪽 중에서</p><br>
	<hr>
	<h5><b><%= @article.user.username %>님의 생각</b></h5>
	<%= simple_format(@article.description) %>
	<hr>
  
	<% if @article.user %>
		<ul class="listing">
			<div class="row center">
				<div class="col-md-4 col-md-offset-4">
					<li>Created by: </li>
					<li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
					<li class="article-title">
						<%= link_to @article.user.username, user_path(@article.user) %>
					</li>
					<li>
						<small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small>
					</li>
				</div>
			</div>
		</ul>
	<% end %>
	
	<div class="article-actions">
		<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
			<%= link_to "수정", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
			<%= link_to "삭제", article_path(@article), method: :delete,
			data: { confirm: "정말 삭제하시겠습니까?"},
			class: "btn btn-xs btn-danger" %>
		<% end %>
		<%= link_to "목록", articles_path, class: "btn btn-xs btn-success" %>
	</div><hr>
	<h3><strong>댓글</strong></h3>
	<%= render 'comments/comment' %>
</div>

app/views/comments/_comment.html.erb
<%= pluralize(@comments.count, "comment") %><hr>

<% @comments.each do |comment| %>
  <p><strong><%= comment.user.username %></strong></p>
  <p><%= comment.content %>&nbsp;&nbsp;
  <% if current_user == comment.user %>
    <%= link_to '삭제', [comment.article, comment], method: :delete %>
      <%= link_to '수정', edit_article_comment_path(comment.article, comment) %></p>
  <% end %>
  <br>
<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for([@article, @article.comments.build], :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-sm-8">
          <%= f.text_area :content, class: "form-control", placeholder: "댓글을 입력하세요 ..." %>
        </div>
        <div class="col-sm-8">
          <%= f.submit("등록") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= form_for([@article, @comment], :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="col-sm-8">
            <%= f.text_area :content, class: "form-control", placeholder: "댓글을 입력하세요 ..." %>
          </div>
          <div class="col-sm-8">
            <%= f.submit("수정") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyrignt &copy; <%= link_to 'Woolim', root_path %> by <a target="_blank" href="https://www.facebook.com/starkying">Kyumin Kim</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to 'About', pages_about_path %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '울림', root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to '울림이란?', pages_about_path %></li>
        <li><%= link_to '모든 글', articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">더 보기 <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to '새 글', new_article_path %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to '로그아웃', logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" 
            aria-expanded="false">프로필 보기 <%= "Admin" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to '프로필 수정', edit_user_path(current_user) %></li>
              <li><%= link_to '프로필 보기', user_path(current_user) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to '로그인', login_path %></li>
          <li><%= link_to '회원가입', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Woolim&nbsp;&mdash;&nbsp;오늘의 독서, 울림을 공유하세요</title>
  <link rel="icon" href="http://www.freeiconspng.com/uploads/book-icon-by-sonoftroll-26.png">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_page?(root_path) and !logged_in? %>
    <%= yield %>
  <% else %>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  <% end %>
</body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">  <!-- 울림 소개 페이지 -->
      <h2><b>울림</b>&nbsp;&mdash;&nbsp;Woolim</h2><br>
      <h5>책을 읽으면서 마음을 콕콕 찌르는 주옥 같은 문장들, 기억하고 계신가요?</h5>
      <h5>울림은 내가 감명 받은 문장을 게시하고, 다른 사람들이 올린 문장들에 대해 자유롭게 이야기 나누는 곳입니다.</h5>
      <h5>멋진 책을 읽은 나의 경험을 모두에게 공유하고, 눈에 띄는 문장들을 통해 새로운 독서 경험을 쌓는 계기도 되었으면 좋겠습니다.</h5><br>
      <h5>현재 회원가입과 기본적인 게시판 기능만 구현한 상태이며,</h5>
      <h5>향후 다음의 사항을 업데이트 할 예정입니다.</h5>
      <ul>
        <li>도서 DB 구축 & 글쓰기 페이지 내 도서 검색&middot;선택 기능</li>
        <li>'좋아요' 등 user의 reaction 기능 추가, 그에 맞는 글 정렬 기준 새롭게 개편</li>
        <li>도서 category 별로 영역 나눔</li>
        <li>디자인 개선</li>
      </ul><br>
      <h5>다른 건의사항이 있으신 분은 하단의 facebook 링크를 통해 연락해 주시면 적극 반영하겠습니다.</h5>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <div class="container">
    <br><br><br><br><br><br><br>
    <h1>오늘의 독서, <br>울림을 공유하세요</h1><br>
    <%= link_to 'Sign up now', signup_path, class: "btn btn-success btn-lg btn-xlarge" %><br><br>
    <div class="jumbotron-login">
      <%= link_to 'Log in', login_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>: 저장하지 못했습니다
          </h2>
          <div class="panel-body">
            <ul>
              <%= obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
    <div class="col-xs-12">
      <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
         <div class="form-group">
             <div class="control-label col-sm-2">
                 <%= f.label :username %>
             </div>
             <div class="col-sm-8">
                 <%= f.text_field :username, class: "form-control", placeholder: "아이디를 입력하세요", autofocus: true %>
             </div>
         </div>
         <div class="form-group">
             <div class="control-label col-sm-2">
                 <%= f.label :email %>
             </div>
             <div class="col-sm-8">
                 <%= f.email_field :email, class: "form-control", placeholder: "이메일을 입력하세요" %>
             </div>
         </div>
         <div class="form-group">
             <div class="control-label col-sm-2">
                 <%= f.label :password %>
             </div>
             <div class="col-sm-8">
                 <%= f.password_field :password, class: "form-control", placeholder: "비밀번호를 입력하세요" %>
             </div>
         </div>
         <div class="form-group">
             <div class="col-sm-offset-2 col-sm-10">
                 <%= f.submit(@user.new_record? ? "가입하기" : "계정 수정", class: 'btn btn-primary btn-lg') %>
             </div>
         </div>
     <% end %>
     <div class="col-xs-4 col-xs-offset-4">
         [ <%= link_to "목록으로 돌아가기", articles_path %> ]
     </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 align="center">울림: 계정 수정하기</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Woolim's Users</h1>
<div align="center">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li>
            <small><%= pluralize(user.articles.count, "article") if user.articles %></small>
          </li>
          <% if logged_in? and current_user.admin? %>
            <li><%= link_to "사용자 삭제", user_path(user), method: :delete,
                   data: { confirm: "정말 이 사용자와 해당 게시글들을 모두 삭제하시겠습니까?" } %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">울림: 회원가입</h1><br><br><hr>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"><%= @user.username %>님의 울림</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<br><br><hr>
<div class="center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user.articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>